#!/bin/bash

ln -s `pwd`/bin/launch /usr/local/bin/launch
cat << 'EOF' > ~/.launchrc
// See https://github.com/nicinabox/launch for docs

{
  "host": "",
  "services": {
  },
  "aliases": {
  }
}
EOF

echo "Finished! Run `launchrc edit` to edit your ~/.launchrc."
