#!/bin/bash

ln -s `pwd`/bin/launch /usr/local/bin/launch
cat << 'EOF' > ~/.launchrc
// See https://github.com/nicinabox/launch for docs

{
  "host": "tower.local",
  "services": {
    // "transmission": ":9091"
  },
  "aliases": {
    // "": "transmission"
  }
}
EOF

echo "Finished! Edit ~/.launchrc"
